Repository issue-tracker-08/issue-tracker-max, pull requests merged in 2023-07, with the labels that each got.

#6 [FE] 프론트 개발 환경 초기 세팅
  fe/.eslintrc.cjs
  fe/.gitignore
  fe/.prettierrc.json
  fe/README.md
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/App.css
  fe/src/App.tsx
  fe/src/index.css
  fe/src/main.tsx
  fe/src/vite-env.d.ts
  fe/tsconfig.json
  fe/tsconfig.node.json
  fe/vite.config.ts
Labels: front-end

#8 #7 design: 디자인 시스템 세팅
  fe/index.html
  fe/public/favicon.png
  fe/src/App.css
  fe/src/App.tsx
  fe/src/assets/icon/Rectangle 16.svg
  fe/src/assets/icon/alertCircle.svg
  fe/src/assets/icon/archive.svg
  fe/src/assets/icon/calendar.svg
  fe/src/assets/icon/checkBoxActive.svg
  fe/src/assets/icon/checkBoxInitial.svg
  fe/src/assets/icon/checkOffCircle.svg
  fe/src/assets/icon/checkOnCircle.svg
  fe/src/assets/icon/chevronDown.svg
  fe/src/assets/icon/edit.svg
  fe/src/assets/icon/label.svg
  fe/src/assets/icon/logo.svg
  fe/src/assets/icon/milestone.svg
  fe/src/assets/icon/paperclip.svg
  fe/src/assets/icon/plus.svg
  fe/src/assets/icon/refreshCcw.svg
  fe/src/assets/icon/search.svg
  fe/src/assets/icon/smile.svg
  fe/src/assets/icon/trash.svg
  fe/src/assets/icon/userImageLarge.svg
  fe/src/assets/icon/userImageSmall.svg
  fe/src/assets/icon/xSquare.svg
  fe/src/components/common/Logo.tsx
  fe/src/index.css
  fe/src/main.tsx
  fe/src/styles/GlobalStyle.tsx
  fe/src/styles/designSystem.ts
  fe/tsconfig.json
Labels: front-end

#2 [BE] DB 스키마 작성
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/schema.sql
Labels: documentation, back-end

#5 [BE] 초기 클래스 파일 작성
  backend/src/main/java/kr/codesquad/issuetracker/comment/domain/Comment.java
  backend/src/main/java/kr/codesquad/issuetracker/issue/domain/Issue.java
  backend/src/main/java/kr/codesquad/issuetracker/label/domain/IssueLabel.java
  backend/src/main/java/kr/codesquad/issuetracker/label/domain/Label.java
  backend/src/main/java/kr/codesquad/issuetracker/milestone/domain/Milestone.java
  backend/src/main/java/kr/codesquad/issuetracker/useraccount/domain/IssueAssignee.java
  backend/src/main/java/kr/codesquad/issuetracker/useraccount/domain/UserAccount.java
Labels: back-end

#13 [FE] Design System
  fe/index.html
  fe/public/favicon.png
  fe/src/App.css
  fe/src/App.tsx
  fe/src/assets/icon/Rectangle 16.svg
  fe/src/assets/icon/alertCircle.svg
  fe/src/assets/icon/archive.svg
  fe/src/assets/icon/calendar.svg
  fe/src/assets/icon/checkBoxActive.svg
  fe/src/assets/icon/checkBoxInitial.svg
  fe/src/assets/icon/checkOffCircle.svg
  fe/src/assets/icon/checkOnCircle.svg
  fe/src/assets/icon/chevronDown.svg
  fe/src/assets/icon/edit.svg
  fe/src/assets/icon/label.svg
  fe/src/assets/icon/logo.svg
  fe/src/assets/icon/milestone.svg
  fe/src/assets/icon/paperclip.svg
  fe/src/assets/icon/plus.svg
  fe/src/assets/icon/refreshCcw.svg
  fe/src/assets/icon/search.svg
  fe/src/assets/icon/smile.svg
  fe/src/assets/icon/trash.svg
  fe/src/assets/icon/userImageLarge.svg
  fe/src/assets/icon/userImageSmall.svg
  fe/src/assets/icon/xSquare.svg
  fe/src/components/common/Logo.tsx
  fe/src/index.css
  fe/src/main.tsx
  fe/src/styles/GlobalStyle.tsx
  fe/src/styles/designSystem.ts
  fe/src/utils/style.ts
  fe/tsconfig.json
Labels: front-end

#18 [FE] Button & Tab Button 컴포넌트 구현
  fe/src/components/common/Button/BaseButton.tsx
  fe/src/components/common/Button/Button.tsx
  fe/src/components/common/Button/ContainerButton.tsx
  fe/src/components/common/Button/GhostButton.tsx
  fe/src/components/common/Button/OutlineButton.tsx
  fe/src/components/common/Button/constants.ts
  fe/src/components/common/Button/index.tsx
  fe/src/components/common/Logo.tsx
  fe/src/components/common/TabBar.tsx
  fe/src/styles/GlobalStyle.tsx
  fe/src/styles/designSystem.ts
Labels: front-end

#19 [BE] 회원가입
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/kr/codesquad/issuetracker/application/AuthService.java
  backend/src/main/java/kr/codesquad/issuetracker/domain/UserAccount.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/ApplicationException.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/ErrorCode.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/ErrorResponse.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/GlobalExceptionHandler.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/config/SecurityConfig.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/persistence/UserAccountRepository.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/security/PasswordEncoder.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/security/SHA256.java
  backend/src/main/java/kr/codesquad/issuetracker/presentation/AuthController.java
  backend/src/main/java/kr/codesquad/issuetracker/presentation/request/SignupRequest.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/kr/codesquad/issuetracker/acceptance/AuthAcceptanceTest.java
  backend/src/test/java/kr/codesquad/issuetracker/acceptance/DatabaseInitializer.java
  backend/src/test/java/kr/codesquad/issuetracker/application/AuthServiceTest.java
  backend/src/test/java/kr/codesquad/issuetracker/fixture/FixtureFactory.java
  backend/src/test/java/kr/codesquad/issuetracker/presentation/AuthControllerTest.java
  backend/src/test/resources/application.yml
Labels: enhancement, back-end

#22 #10 fix: Button Component Styled-component Warning 해결
  fe/src/components/common/Button/Button.tsx
  fe/src/components/common/Button/ContainerButton.tsx
  fe/src/components/common/Button/GhostButton.tsx
  fe/src/components/common/Button/OutlineButton.tsx
Labels: front-end

#25 [FE] FilterBar 컴포넌트 UI 구현
  fe/src/App.tsx
  fe/src/components/Dropdown/DropdownIndicator.tsx
  fe/src/components/Dropdown/DropdownPanel.tsx
  fe/src/components/Dropdown/types.ts
  fe/src/components/FilterBar.tsx
Labels: front-end

#23 [FE] Text Input Component UI
  fe/src/App.tsx
  fe/src/components/common/TextInput.tsx
  fe/src/styles/GlobalStyle.tsx
Labels: front-end

#27 [FE] TextInput placeholder state & style 수정
  fe/src/components/common/TextInput.tsx
Labels: front-end

#24 [BE] 로그인
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/kr/codesquad/config/JwtConfig.java
  backend/src/main/java/kr/codesquad/issuetracker/application/AuthService.java
  backend/src/main/java/kr/codesquad/issuetracker/domain/UserAccount.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/ErrorCode.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/ErrorResponse.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/GlobalExceptionHandler.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/config/SecurityConfig.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/config/jwt/Jwt.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/config/jwt/JwtProperties.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/persistence/UserAccountRepository.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/security/hash/PasswordEncoder.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/security/hash/SHA256.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/security/jwt/JwtProvider.java
  backend/src/main/java/kr/codesquad/issuetracker/presentation/AuthController.java
  backend/src/main/java/kr/codesquad/issuetracker/presentation/request/LoginRequest.java
  backend/src/main/java/kr/codesquad/issuetracker/presentation/response/TokenResponse.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/kr/codesquad/issuetracker/ApplicationTest.java
  backend/src/test/java/kr/codesquad/issuetracker/DatabaseInitializerExtension.java
  backend/src/test/java/kr/codesquad/issuetracker/acceptance/AuthAcceptanceTest.java
  backend/src/test/java/kr/codesquad/issuetracker/acceptance/DatabaseInitializer.java
  backend/src/test/java/kr/codesquad/issuetracker/application/AuthServiceTest.java
  backend/src/test/java/kr/codesquad/issuetracker/application/unit/AuthServiceTest.java
  backend/src/test/java/kr/codesquad/issuetracker/fixture/FixtureFactory.java
  backend/src/test/java/kr/codesquad/issuetracker/infrastructure/security/hash/SHA256Test.java
  backend/src/test/java/kr/codesquad/issuetracker/presentation/AuthControllerTest.java
Labels: enhancement, back-end

#29 [FE] Routing & MSW
  fe/package-lock.json
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/App.tsx
  fe/src/api/index.ts
  fe/src/main.tsx
  fe/src/mocks/browser.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/AuthPage.tsx
  fe/src/pages/Dashboard.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/SignupPage.tsx
Labels: front-end

#34 [FE] MainPage 초기 구현
  fe/src/App.tsx
  fe/src/assets/icon/moon.svg
  fe/src/assets/icon/sun.svg
  fe/src/components/Dropdown/DropdownIndicator.tsx
  fe/src/components/Dropdown/DropdownItem.tsx
  fe/src/components/FilterBar.tsx
  fe/src/components/Header.tsx
  fe/src/components/Issues/IssueItem.tsx
  fe/src/components/Table/Table.tsx
  fe/src/components/Table/TableBody.tsx
  fe/src/components/Table/TableBodyIssues.tsx
  fe/src/components/Table/TableHeader.tsx
  fe/src/components/Table/TableHeaderIssues.tsx
  fe/src/components/Table/index.ts
  fe/src/components/common/Button/GhostButton.tsx
  fe/src/components/common/Input/InputCheckbox.tsx
  fe/src/components/common/Input/InputRadio.tsx
  fe/src/components/common/Logo.tsx
  fe/src/components/common/TabBar.tsx
  fe/src/components/common/ToggleSwitch.tsx
  fe/src/pages/Dashboard.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/MainPage/IssuesPage.tsx
  fe/src/pages/MainPage/MainPage.tsx
Labels: front-end

#35 [FE] 회원가입, 로그인 페이지 UI & mock API 구성
  fe/src/App.tsx
  fe/src/api/index.ts
  fe/src/components/common/Button/constants.ts
  fe/src/components/common/TextInput.tsx
  fe/src/hooks/useInput.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/AuthPage.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/SignupPage.tsx
  fe/src/styles/GlobalStyle.tsx
Labels: front-end

#32 [BE] JWT 검증 로직
  backend/src/main/java/kr/codesquad/issuetracker/exception/ErrorCode.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/config/SecurityConfig.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/security/jwt/JwtProvider.java
  backend/src/main/java/kr/codesquad/issuetracker/presentation/filter/ExceptionHandlerFilter.java
  backend/src/main/java/kr/codesquad/issuetracker/presentation/filter/JwtFilter.java
  backend/src/test/java/kr/codesquad/issuetracker/infrastructure/security/jwt/JwtProviderTest.java
Labels: enhancement, back-end

#33 [BE] 이슈 목록 조회 API
  backend/src/main/java/kr/codesquad/issuetracker/application/IssueService.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/persistence/IssueRepository.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/persistence/mapper/IssueSimpleMapper.java
  backend/src/main/java/kr/codesquad/issuetracker/presentation/IssueController.java
  backend/src/main/resources/data.sql
  backend/src/test/java/kr/codesquad/issuetracker/acceptance/DatabaseInitializer.java
  backend/src/test/java/kr/codesquad/issuetracker/application/IssueServiceTest.java
Labels: enhancement, back-end

#36 [FE] Button Component 리팩토링
  fe/src/components/Table/TableHeaderIssues.tsx
  fe/src/components/common/Button/Button.tsx
  fe/src/components/common/Button/ContainerButton.tsx
  fe/src/components/common/Button/GhostButton.tsx
  fe/src/components/common/Button/OutlineButton.tsx
  fe/src/pages/MainPage/IssuesPage.tsx
Labels: front-end

#37 [FE] 1주차 리뷰 반영 리팩토링
  .gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/api/fetcher.ts
  fe/src/api/index.ts
Labels: front-end

#40 [BE] 리뷰사항 반영
  backend/src/main/java/kr/codesquad/config/JwtConfig.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/config/jwt/Jwt.java
  backend/src/main/java/kr/codesquad/issuetracker/infrastructure/security/jwt/JwtProvider.java
  backend/src/main/java/kr/codesquad/issuetracker/presentation/filter/JwtFilter.java
  backend/src/main/resources/docker.yml
  backend/src/test/java/kr/codesquad/issuetracker/acceptance/AuthAcceptanceTest.java
  backend/src/test/java/kr/codesquad/issuetracker/application/AuthServiceTest.java
  backend/src/test/java/kr/codesquad/issuetracker/application/unit/AuthServiceTest.java
  backend/src/test/java/kr/codesquad/issuetracker/infrastructure/security/jwt/JwtProviderTest.java
Labels: back-end

#42 #38 feat: 로그인 구현
  fe/src/App.tsx
  fe/src/api/fetcher.ts
  fe/src/api/index.ts
  fe/src/components/common/Button/Button.tsx
  fe/src/context/authContext.tsx
  fe/src/main.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/Auth/AuthPage.tsx
  fe/src/pages/Auth/LoginPage.tsx
  fe/src/pages/Auth/SignupPage.tsx
Labels: front-end
